apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bt-otel-collector-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bt-otel-collector-helm.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bt-otel-collector-helm.fullname" . }}
  labels:
    {{- include "bt-otel-collector-helm.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bt-otel-collector-helm.fullname" . }}
  labels:
    {{- include "bt-otel-collector-helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bt-otel-collector-helm.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "bt-otel-collector-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
